apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synergychat-api-pvc
  namespace: crawler
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
